# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telatransferir.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class TelaTransferir(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelSacar = QtWidgets.QLabel(self.centralwidget)
        self.labelSacar.setGeometry(QtCore.QRect(400, 100, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelSacar.setFont(font)
        self.labelSacar.setObjectName("labelSacar")
        self.btnTransferir = QtWidgets.QPushButton(self.centralwidget)
        self.btnTransferir.setGeometry(QtCore.QRect(400, 300, 91, 31))
        self.btnTransferir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnTransferir.setObjectName("btnTransferir")
        self.btnSair = QtWidgets.QPushButton(self.centralwidget)
        self.btnSair.setGeometry(QtCore.QRect(40, 450, 91, 31))
        self.btnSair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSair.setObjectName("btnSair")
        self.btnVoltar = QtWidgets.QPushButton(self.centralwidget)
        self.btnVoltar.setGeometry(QtCore.QRect(40, 400, 91, 31))
        self.btnVoltar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnVoltar.setObjectName("btnVoltar")
        self.lineEditTransferir = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditTransferir.setGeometry(QtCore.QRect(400, 190, 151, 21))
        self.lineEditTransferir.setObjectName("lineEditTransferir")
        self.lineEditConta = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditConta.setGeometry(QtCore.QRect(400, 250, 151, 21))
        self.lineEditConta.setObjectName("lineEditConta")
        self.labelValor = QtWidgets.QLabel(self.centralwidget)
        self.labelValor.setGeometry(QtCore.QRect(400, 160, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelValor.setFont(font)
        self.labelValor.setObjectName("labelValor")
        self.labelConta = QtWidgets.QLabel(self.centralwidget)
        self.labelConta.setGeometry(QtCore.QRect(400, 220, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelConta.setFont(font)
        self.labelConta.setObjectName("labelConta")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 652, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelSacar.setText(_translate("MainWindow", "Transferir"))
        self.btnTransferir.setText(_translate("MainWindow", "Transferir"))
        self.btnSair.setText(_translate("MainWindow", "Sair"))
        self.btnVoltar.setText(_translate("MainWindow", "Voltar"))
        self.labelValor.setText(_translate("MainWindow", "Valor"))
        self.labelConta.setText(_translate("MainWindow", "Conta"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = TelaTransferir()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
