-- MySQL Script generated by MySQL Workbench
-- Tue Dec 13 19:56:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema telefonia
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `telefonia` ;

-- -----------------------------------------------------
-- Schema telefonia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `telefonia` DEFAULT CHARACTER SET utf8 ;
USE `telefonia` ;

-- -----------------------------------------------------
-- Table `telefonia`.`vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `telefonia`.`vendedor` ;

CREATE TABLE IF NOT EXISTS `telefonia`.`vendedor` (
  `idVendedor` INT NOT NULL AUTO_INCREMENT,
  `nomeVendedor` VARCHAR(45) NOT NULL,
  `enderecoVendedor` TINYTEXT NOT NULL,
  `telefoneVendedor` INT(11) NOT NULL,
  `emailVendedor` VARCHAR(50) NOT NULL,
  `salarioVendedor` FLOAT NOT NULL,
  `comissaoVendedor` FLOAT NULL,
  PRIMARY KEY (`idVendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telefonia`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `telefonia`.`cliente` ;

CREATE TABLE IF NOT EXISTS `telefonia`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(45) NOT NULL,
  `enderecoCliente` TINYTEXT NOT NULL,
  `telefoneCliente` INT(11) NOT NULL,
  `emailCliente` VARCHAR(50) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telefonia`.`plano`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `telefonia`.`plano` ;

CREATE TABLE IF NOT EXISTS `telefonia`.`plano` (
  `idPlano` INT NOT NULL AUTO_INCREMENT,
  `nomePlano` VARCHAR(45) NOT NULL,
  `tipoPlano` ENUM('voz', 'internet') NOT NULL,
  `valorPlano` FLOAT NOT NULL,
  `duracaoPlano` INT(2) NOT NULL,
  PRIMARY KEY (`idPlano`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telefonia`.`contratarPlano`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `telefonia`.`contratarPlano` ;

CREATE TABLE IF NOT EXISTS `telefonia`.`contratarPlano` (
  `idPlano` INT NOT NULL AUTO_INCREMENT,
  `dataContrato` DATETIME NOT NULL,
  `numeroAparelhoContrato` INT(11) NOT NULL,
  `vendedor_idVendedor` INT NOT NULL,
  `cliente_idCliente` INT NOT NULL,
  `plano_idPlano` INT NOT NULL,
  PRIMARY KEY (`idPlano`, `vendedor_idVendedor`, `cliente_idCliente`, `plano_idPlano`),
  INDEX `fk_contratarPlano_vendedor_idx` (`vendedor_idVendedor` ASC) VISIBLE,
  INDEX `fk_contratarPlano_cliente1_idx` (`cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_contratarPlano_plano1_idx` (`plano_idPlano` ASC) VISIBLE,
  CONSTRAINT `fk_contratarPlano_vendedor`
    FOREIGN KEY (`vendedor_idVendedor`)
    REFERENCES `telefonia`.`vendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contratarPlano_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `telefonia`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contratarPlano_plano1`
    FOREIGN KEY (`plano_idPlano`)
    REFERENCES `telefonia`.`plano` (`idPlano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telefonia`.`aparelho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `telefonia`.`aparelho` ;

CREATE TABLE IF NOT EXISTS `telefonia`.`aparelho` (
  `idAparelho` INT NOT NULL AUTO_INCREMENT,
  `modeloAparelho` VARCHAR(45) NOT NULL,
  `precoAparelho` FLOAT NOT NULL,
  PRIMARY KEY (`idAparelho`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `telefonia`.`venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `telefonia`.`venda` ;

CREATE TABLE IF NOT EXISTS `telefonia`.`venda` (
  `idVenda` INT NOT NULL AUTO_INCREMENT,
  `dataVenda` DATETIME NOT NULL,
  `vendedor_idVendedor` INT NOT NULL,
  `cliente_idCliente` INT NOT NULL,
  `aparelho_idAparelho` INT NOT NULL,
  PRIMARY KEY (`idVenda`, `vendedor_idVendedor`, `cliente_idCliente`, `aparelho_idAparelho`),
  INDEX `fk_venda_vendedor1_idx` (`vendedor_idVendedor` ASC) VISIBLE,
  INDEX `fk_venda_cliente1_idx` (`cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_venda_aparelho1_idx` (`aparelho_idAparelho` ASC) VISIBLE,
  CONSTRAINT `fk_venda_vendedor1`
    FOREIGN KEY (`vendedor_idVendedor`)
    REFERENCES `telefonia`.`vendedor` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `telefonia`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_aparelho1`
    FOREIGN KEY (`aparelho_idAparelho`)
    REFERENCES `telefonia`.`aparelho` (`idAparelho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
