# Usar a imagem base do Python
FROM python:3.9

# Copiar os arquivos para o container
COPY checksum.py /app/checksum.py
COPY sender.py /app/sender.py

# Definir o diretório de trabalho
WORKDIR /app

# Comando para rodar o processo sender
CMD ["python", "sender.py"]
