# Usar a imagem base do Python
FROM python:3.9

# Copiar os arquivos para o container
COPY checksum.py /app/checksum.py
COPY receiver.py /app/receiver.py

# Definir o diretório de trabalho
WORKDIR /app

# Comando para rodar o processo receiver
CMD ["python", "receiver.py"]
